# Utilise l'image officielle Node.js
FROM node:16

# Crée et définit le répertoire de l'application
WORKDIR /usr/src/app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install express nodemon mongoose 

# Copie tout le reste du code de l'application
COPY . .

# Expose le port sur lequel l'application va écouter
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "index.js"]
